{{ __('user-list') }}
{{ __('user-create') }}
{{ __('user-edit') }}
{{ __('user-delete') }}
{{ __('role-list') }}
{{ __('role-create') }}
{{ __('role-edit') }}
{{ __('role-delete') }}
{{ __('topic-list') }}
{{ __('topic-create') }}
{{ __('topic-edit') }}
{{ __('topic-delete') }}
{{ __('essay-list') }}
{{ __('essay-create') }}
{{ __('essay-edit') }}
{{ __('essay-delete') }}
{{ __('user') }}
{{ __('role') }}
{{ __('topic') }}
{{ __('essay') }}
{{ __('opponent') }}
{{ __('opponent-sendrequest') }}
{{ __('opponent-confirmation') }}
{{ __('Admin') }}
{{ __('Teacher') }}